apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - name: httpd-webserver
    port: 80
    nodePort: 31000
    targetPort: 80
    protocol: TCP
  - name: tomcat-server
    port: 8080
    nodePort: 32000
    targetPort: 8080
    protocol: TCP
  selector:
    env: prod
